extends: airbnb-base
env:
  node: true
  mocha: true
  es6: true
rules:
  semi:
    - 'error'
    - 'never'
  indent:
    - 'error'
    - 'tab'
  no-tabs: 'off'
  func-names:
    - 'error'
    - 'never'